#!/bin/bash
#PBS -N U5
#PBS -l walltime=24:00:00
#PBS -l 'nodes=3:ppn=16'
#PBS -q short
#PBS -j eo

# goto workdir
cd "$PBS_O_WORKDIR"
casedir=$(pwd)

# get number of processors
nprocs=$(cat $PBS_NODEFILE | wc -l)
# start solver
mpiexec -np $nprocs foamExec faceAgglomerate -region air -parallel >log.faceAgglomerate
mpiexec -np $nprocs foamExec viewFactorsGenUpdated -region air -parallel >log.viewFactorsGenUpdated
mpiexec -np $nprocs foamExec solarRayTracingGen -region air -parallel >log.solarRayTracingGen
mpiexec -np $nprocs foamExec urbanMicroclimateFoam -parallel >log
