#!/bin/bash
#PBS -N reconstr
#PBS -l walltime=12:00:00
#PBS -l 'nodes=1:ppn=1'
#PBS -q infinijazz
#PBS -j eo

# goto workdir
cd "$PBS_O_WORKDIR"
casedir=$(pwd)

# get number of processors
nprocs=$(cat $PBS_NODEFILE | wc -l)
# start solver
foamExec reconstructParDelReady -allRegions -newTimes
