#!/bin/bash

# src files
srcPath=(
    src/turbulenceModels/incompressible/RAS
    src/vegetationModels
    src/finiteVolume
)

utilPath=(
    applications/utilities/rayTracing
    applications/utilities/preProcessing/calcLAI
    applications/utilities/postProcessing/cellV
    applications/utilities/postProcessing/fieldIntegrate
    applications/utilities/postProcessing/fieldMinMax
    applications/utilities/postProcessing/gradU
    #applications/utilities/postProcessing/heatFluxIncompressible
    applications/utilities/postProcessing/moisture/hmoist
    applications/utilities/postProcessing/moisture/heatFluxMoist
    #applications/utilities/postProcessing/moisture/qToRH
    #applications/utilities/postProcessing/moisture/RHToq
    applications/utilities/postProcessing/postAvg
)

appPath=(
    applications/solvers/bbbigleafFoam
    #applications/solvers/bigleafFoam
    #applications/solvers/nuSimpleFoam
    #applications/solvers/transientbbbigleafFoam
    applications/solvers/simplifiedVegetation
    applications/solvers/buoyantBoussinesqVegetationSimpleFoam
)

extPath=(
    external/blockmeshdg
)

parentDir=$(pwd)

# clean src
echo "------------------------------------"
echo "C L E A N I N G    S R C   F I L E S"
echo "------------------------------------"
for i in "${srcPath[@]}"
  do
    cd $i
    echo -n "Cleaning.....$i"
    wclean
    cd $parentDir
    echo ".....Done."
done
echo ""

# clean src
echo "---------------------------------------"
echo "C L E A N I N G    U T I L    F I L E S"
echo "---------------------------------------"
for i in "${utilPath[@]}"
  do
    cd $i
    echo -n "Cleaning.....$i"
    wclean
    cd $parentDir
    echo ".....Done."
done
echo ""

# clean ext
echo "-------------------------------------"
echo "C L E A N I N G    E X T    F I L E S"
echo "-------------------------------------"
for i in "${extPath[@]}"
  do
    cd $i
    echo "Cleaning.....$i"
    ./Allwclean
    cd $parentDir
done
echo ""


# clean apps
echo "------------------------------------------"
echo "C L E A N I N G    S O L V E R   F I L E S"
echo "------------------------------------------"
for i in "${appPath[@]}"
  do
    cd $i
    echo -n "Cleaning.....$i"
    wclean
    cd $parentDir
    echo ".....Done."
done
echo "All done."
