#!/bin/bash

# src files
srcPath=(
    src/turbulenceModels/incompressible/RAS
    src/vegetationModels
    src/finiteVolume
)

utilPath=(
    applications/utilities/postProcessing/cellV
    applications/utilities/postProcessing/fieldIntegrate
    applications/utilities/postProcessing/fieldMinMax
    applications/utilities/postProcessing/gradU
    #applications/utilities/postProcessing/heatFluxIncompressible
    applications/utilities/postProcessing/moisture/hmoist
    applications/utilities/postProcessing/moisture/heatFluxMoist
    #applications/utilities/postProcessing/moisture/qToRH
    #applications/utilities/postProcessing/moisture/RHToq
)

appPath=(
    # applications/solvers/bigleafFoam
    applications/solvers/bbbigleafFoam
    # applications/solvers/transientbbbigleafFoam
)

extPath=(
    external/blockmeshdg
)

parentDir=$(pwd)

# compile src
echo "-----------------------------------"
echo "C O M P I L E    S R C   F I L E S"
echo "----------------------------------"
for i in "${srcPath[@]}"
  do
    cd $i
    echo "Compiling.....$i"
    wmake libso
    cd $parentDir
done
echo ""

# compile util
echo "-------------------------------------"
echo "C O M P I L E    U T I L    F I L E S"
echo "-------------------------------------"
for i in "${utilPath[@]}"
  do
    cd $i
    echo "Compiling.....$i"
    wmake
    cd $parentDir
done
echo ""

# compile ext
echo "-----------------------------------"
echo "C O M P I L E    E X T    F I L E S"
echo "-----------------------------------"
for i in "${extPath[@]}"
  do
    cd $i
    echo "Compiling.....$i"
    ./Allwmake
    cd $parentDir
done
echo ""

# compile solver
echo "-----------------------------------------"
echo "C O M P I L E    S O L V E R   F I L E S"
echo "----------------------------------------"
for i in "${appPath[@]}"
  do
    cd $i
    echo "Compiling.....$i"
    wmake
    cd $parentDir
done
echo "All done."
