#!/bin/bash

# src files
srcPath=(
    turbulenceModels/incompressible/RAS
    vegetationModels
)

appPath=(
    solvers/bigleafFoam
)

parentDir=$(pwd)

# clean src
echo "-----------------------------------"
echo "C O M P I L E    S R C   F I L E S"
echo "----------------------------------"
cd src
srcParentDir=$(pwd)
for i in "${srcPath[@]}"
  do
    cd $i
    echo "Compiling..........$i"
    wmake libso
    cd $srcParentDir
    echo "Done."
done
cd $parentDir
echo ""


# clean apps
echo "-----------------------------------------"
echo "C O M P I L E    S O L V E R   F I L E S"
echo "----------------------------------------"
cd applications
appParentDir=$(pwd)
for i in "${appPath[@]}"
  do
    cd $i
    echo "Compiling..........$i"
    wmake
    cd $appParentDir
    echo "Done."
done
cd $parentDir
echo ""

echo "All done."
