#!/bin/bash

# src files
srcPath=(
    src/turbulenceModels/incompressible/RAS
    src/vegetationModels
)

utilPath=(
    applications/utilities/postProcessing/velocityField/gradU
)

appPath=(
    applications/solvers/bigleafFoam
)

parentDir=$(pwd)

# clean src
echo "------------------------------------"
echo "C L E A N I N G    S R C   F I L E S"
echo "------------------------------------"
for i in "${srcPath[@]}"
  do
    cd $i
    echo -n "Cleaning.....$i"
    wclean
    cd $parentDir
    echo ".....Done."
done
echo ""

# clean src
echo "---------------------------------------"
echo "C L E A N I N G    U T I L    F I L E S"
echo "---------------------------------------"
for i in "${utilPath[@]}"
  do
    cd $i
    echo -n "Cleaning.....$i"
    wclean
    cd $parentDir
    echo ".....Done."
done
echo ""


# clean apps
echo "------------------------------------------"
echo "C L E A N I N G    S O L V E R   F I L E S"
echo "------------------------------------------"
for i in "${appPath[@]}"
  do
    cd $i
    echo -n "Cleaning.....$i"
    wclean
    cd $parentDir
    echo ".....Done."
done
echo "All done."
