#!/bin/bash

# Copy initial conditions
echo -n "Copying IC..."
rm -rf 0
cp -r 0.org 0
echo "Done."

# Mesh generation
echo -n "Generating mesh..."
#./makeMesh | gzip > log.makeMesh.gz
echo "Done."

# Setting fields: LAD
echo -n "Setting LAD..."
funkySetFields -time 0
echo "Done."

# Calculate Leaf area Index
echo -n "Setting LAI..."
calcLAI3D

echo "Done!"
