#!/bin/bash

# Generate blockMeshDict
python blockMeshDictGen.py

# Generate msh
# blockMesh
blockMeshDG

# mirror mesh
# mirrorMesh

# rotate mesh

# checkMesh
checkMesh

# Create baffle zones
# topoSet

# Create baffle
# createBaffles -overwrite
