#!/bin/bash


nproc=4

# Calculate Leaf area Index
echo "decompose domain "
pyFoamDecompose.py . $nproc

# faceAgglomerate
echo "faceAgglomerate ..."
mpiexec -np $nproc foamExec faceAgglomerate -parallel

# viewFactorsGenUpdated
echo "viewFactorsGenUpdated ..."
mpiexec -np $nproc foamExec viewFactorsGenUpdated -parallel

# calculated LAI
echo "Calculating LAI ..."
mpiexec -np $nproc foamExec calcLAI -parallel

# solarRayTracingVegGen 
mpiexec -np $nproc foamExec solarRayTracingVegGen -parallel
echo "Done!"
