#!/bin/sh

# Directory and files to remove
dirs="Decomposer.* PyFoam* logs postProcessing [1-9]* processor* 0"
files="log.* *.foam Decomposer* PyFoam* PlyParser* *.OpenFOAM"

# Delete files
for file in $files; do
    if [ -f $file ]; then
        rm $file -v
    fi
done

# Delete directories
for dir in $dirs; do
    if  [ -d $dir ]; then
        rm -rv $dir
    fi
done

cd constant
rm -v construct* F.gz final* global* LAI* sky* subMap* sunViewCoeff* sunVisibleOrNot* sunskyMap* cellToRegion*
rm -rv extendedFeatureEdgeMesh

cd polyMesh
rm -rv sets
rm -r boundary  cellZones  face*  neighbour  owner  point* *.gz
