#!/bin/bash
# Script to run batch case on hypatia
# Lento Manickathan <lento.manickathan@gmail.com>, <lento.manickathan@emap.ch>

# User options -----
# wall time
walltime=24:00:00
# number of nodes
nodes=1
# queue type (short, medium, single_medium, long, huge, newshort, infinijazz, infiniband)
queue=newshort
# job status mailing address
email=lento.manickathan@empa.ch

# Batch job parameters ----

# Ideal (maximum ppn)
#if [ $queue == short ] || [ $queue == medium ] || [ $queue == single_medium ] || [ $queue == long ] || [ $queue == huge ]; then
#    ppn=16
#elif [ $queue == newshort ]; then
#    ppn=20
#elif [ $queue == infinijazz ] || [ $queue == infiniband ]; then
#    ppn=8
#else
#    ppn=1 # single ppn per node, for example serial jobs
#fi

# custom
ppn=20

# Total processors
nprocs=$(($nodes*$ppn))
# work directory
workdir=$(pwd)
# Job name
jobname=$(basename $workdir)

# Submit job ----
qsub -d $workdir -j oe -l nodes=$nodes:ppn=$ppn,walltime=$walltime -m abe -M $email -N $jobname -q $queue runCase -v numProc=$nprocs
