#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

set -x

wmake $makeType buildingMaterialModel
wmake $makeType simpleControlFluid
wmake $makeType solarLoadModel
wmake $makeType turbulenceModels/compressible/RAS
wmake $makeType vegetationModels

