#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

set -x

wclean buildingMaterialModel
wclean simpleControlFluid
wclean solarLoadModel
wclean turbulenceModels/compressible/RAS
wclean vegetationModels
