#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -x

wmake solarRaysThroughVegGen
wmake solarRayTracingVegGen
wmake solarRayTracingVegGenNew

wmake solarRayTracingGen
wmake faceAgglomerateNew

wmake viewFactorsGenSky
wmake viewFactorsGenUpdated
wmake viewFactorsGenUpdatedNew
wmake solarRayTracingGenCyclic
wmake viewFactorsGenUpdatedCyclic
wmake viewFactorsGenUpdatedCyclicSky

wmake calculateqrsw
wmake calcSf
wmake calculateTmrt
wmake calculateTmrtVeg
wmake fieldAvgRoot
wmake fieldMinMax
wmake refineMeshCustom
wmake wtoRH
