#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -x

#wmake calculateUTCI

wmake faceAgglomerateNew
wmake solarRayTracingVegGenNew
wmake viewFactorsGenUpdatedNew

wmake solarRayTracingGen
wmake solarRayTracingVegGen
wmake solarRaysThroughVegGen
wmake solarRayTracingGenCyclic
wmake viewFactorsGenSky
wmake viewFactorsGenUpdated
wmake viewFactorsGenUpdatedCyclic
wmake viewFactorsGenUpdatedCyclicSky

