#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -x

wclean calculateUTCI
wclean solarRayTracingGen
wclean solarRayTracingVegGen
wclean solarRaysThroughVegGen
wclean solarRayTracingGenCyclic
wclean viewFactorsGenSky
wclean viewFactorsGenUpdated
wclean viewFactorsGenUpdatedCyclic
wclean viewFactorsGenUpdatedCyclicSky

